spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
# Spring读取配置文件中数据：@Value("${user.address.max-count}")
user:
  address:
    max-count: 12

mybatis:
  # mapper????, classpath?????resources???
  mapper-locations: classpath:/com/cy/store/mapper/*.xml
  # ??????
  configuration:
    map-underscore-to-camel-case: true
  # ??
  type-aliases-package: com.cy.store.entity
